### ISSUE TITLE
Redirect users upon first registration

### ISSUE THREAD

**Issue by Ala-Na** [Reaster0/ft_transcendence#46]
Redirect users from backend upon first registration to the modify info page.

**Comment by Reaster0** [comment]
that's a duty shared by frontend and backend, with the system of 2fa implemented in the frontend you will not be hable to redirect correctly when 2fa is enable (because 2fa check is in the login page and just send a basic post request to the back not a full redirection to the back as the 42auth would do), and such you should probably send me a hint so i redirect the client somewhere (maybe a "newuser" field in the user json? don't know)

**Comment by LesChats** [comment]
Sad to add an data base field just for a corner case. I hope we find a better solution regarding that issue. Maybe juste modifying the rerun answer to communicate the info to front (I.e going from returning a user to returning a tuple (user, new: boolean))

**Comment by Reaster0** [comment]
yeah that could make the thing, i just want a hint it don't have to be in the db

**Comment by Ala-Na** [comment]
Maybe I'm not understanding correctly here, but is the redirection only problematic when 2FA is enable upon first connection/registration ?
Because, that case should never happens as 2FA should be disabled by default and activated later if the user wish it (or at least, that's what I understand from the subject). Of course, the user should be able to choose to activate 2FA at the end of his registration, as he will also have options to change his nickname or avatar.

Btw, @LesChats is it normal that the route to enable 2FA was commented and just containing a `return` statement ? I deleted it in last PR that I made, but I can always retrieve it

**Comment by LesChats** [comment]
It is donne
